import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus, Settings, Trash2 } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { notify } from '../../lib/notify'
import { db } from '../../lib/supabase'
import type { Category, Settings as SettingsType, Visibility } from '../../lib/types'
import { slugify } from '../../lib/utils'
import { AdminEmpty } from './AdminDashboard'

export function SettingsAdminPage() {
  const qc = useQueryClient(); const [siteName, setSiteName] = useState('LilKank'); const [tagline, setTagline] = useState('Meu espaço digital'); const [allowRegistration, setAllowRegistration] = useState(true); const [requireAuth, setRequireAuth] = useState(true); const [defaultVisibility, setDefaultVisibility] = useState<Visibility>('private'); const [categoryName, setCategoryName] = useState('')
  const { data } = useQuery({ queryKey: ['admin-settings'], queryFn: async () => {
    const [settings, categories] = await Promise.all([db.from('lilkank_settings').select('*').eq('id', 1).maybeSingle(), db.from('lilkank_categories').select('*').order('sort_order')])
    return { settings: settings.data as SettingsType | null, categories: (categories.data || []) as Category[] }
  } })
  useEffect(() => { if (!data?.settings) return; setSiteName(data.settings.site_name); setTagline(data.settings.site_tagline); setAllowRegistration(data.settings.allow_registration); setRequireAuth(data.settings.require_auth_for_downloads); setDefaultVisibility(data.settings.default_visibility) }, [data?.settings])
  const save = useMutation({ mutationFn: async () => { const { error } = await db.from('lilkank_settings').update({ site_name: siteName.trim() || 'LilKank', site_tagline: tagline.trim() || 'Meu espaço digital', allow_registration: allowRegistration, require_auth_for_downloads: requireAuth, default_visibility: defaultVisibility }).eq('id', 1); if (error) throw error }, onSuccess: () => { qc.invalidateQueries({ queryKey: ['admin-settings'] }); qc.invalidateQueries({ queryKey: ['home'] }); notify('Configurações salvas.') }, onError: (e: Error) => notify(e.message, 'error') })
  const createCategory = async (event: FormEvent) => { event.preventDefault(); const name = categoryName.trim(); if (!name) return; const slug = slugify(name); if (!slug) return; const max = Math.max(0, ...(data?.categories || []).map((c) => c.sort_order)); const { error } = await db.from('lilkank_categories').insert({ name, slug, sort_order: max + 10, active: true }); if (error) return notify(error.message, 'error'); setCategoryName(''); qc.invalidateQueries({ queryKey: ['admin-settings'] }); notify('Categoria criada.') }
  const toggleCategory = async (category: Category) => { const { error } = await db.from('lilkank_categories').update({ active: !category.active }).eq('id', category.id); if (error) return notify(error.message, 'error'); qc.invalidateQueries({ queryKey: ['admin-settings'] }) }
  const removeCategory = async (category: Category) => { if (!window.confirm(`Excluir a categoria “${category.name}”? Os itens ficarão sem categoria.`)) return; const { error } = await db.from('lilkank_categories').delete().eq('id', category.id); if (error) return notify(error.message, 'error'); qc.invalidateQueries({ queryKey: ['admin-settings'] }); notify('Categoria removida.') }
  return <>
    <div className="admin-page-head"><div><small>Sistema</small><h1>Configurações</h1><p>Preferências globais do site, cadastro e regras padrão de download.</p></div><span className="big-icon"><Settings size={21} /></span></div>
    <div className="admin-grid"><section className="panel"><div className="panel-title"><h3>Configurações gerais</h3></div><div className="form-grid"><label>Nome do site<input value={siteName} onChange={(e) => setSiteName(e.target.value)} /></label><label>Frase principal<input value={tagline} onChange={(e) => setTagline(e.target.value)} /></label><label>Visibilidade padrão<select value={defaultVisibility} onChange={(e) => setDefaultVisibility(e.target.value as Visibility)}><option value="private">Privado</option><option value="public">Público</option><option value="members">Cadastrados</option><option value="unlisted">Não listado</option></select></label><div /><label className="switch-line full"><input type="checkbox" checked={allowRegistration} onChange={(e) => setAllowRegistration(e.target.checked)} /><span>Permitir novos cadastros</span></label><label className="switch-line full"><input type="checkbox" checked={requireAuth} onChange={(e) => setRequireAuth(e.target.checked)} /><span>Exigir login globalmente para downloads</span></label><div className="full"><button className="btn btn-primary" onClick={() => save.mutate()} disabled={save.isPending}>Salvar configurações</button></div></div></section>
      <section className="panel"><div className="panel-title"><h3>Categorias</h3></div><form className="toolbar" onSubmit={createCategory}><input style={{ flex: 1 }} value={categoryName} onChange={(e) => setCategoryName(e.target.value)} placeholder="Nova categoria" /><button className="btn btn-primary btn-small"><Plus size={14} />Adicionar</button></form><div className="list-stack" style={{ marginTop: 14 }}>{data?.categories.length ? data.categories.map((category) => <div className="manage-row" key={category.id}><div className="row-main"><strong>{category.name}</strong><small>{category.slug} · {category.active ? 'ativa' : 'oculta'}</small></div><div className="row-actions"><button className="btn btn-outline btn-small" onClick={() => toggleCategory(category)}>{category.active ? 'Ocultar' : 'Ativar'}</button><button className="btn btn-outline btn-small" onClick={() => removeCategory(category)}><Trash2 size={13} /></button></div></div>) : <AdminEmpty text="Nenhuma categoria cadastrada." />}</div></section></div>
  </>
}
